import {
  PROJECT_1_URL,
  PROJECT_1_GITHUB,
  PROJECT_2_URL,
  PROJECT_2_GITHUB,
  PROJECT_3_URL,
  PROJECT_3_GITHUB,
  PROJECT_4_URL,
  PROJECT_4_GITHUB,
} from "./env";

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "Botlock",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1,
          name: "Botlock Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "An enforce-at-the-protocol-layer AI agent scraper wall. Gated content that requests USDC micropayments directly via Solana SPL when crawled by bots.",
            "Integrates HTTP 402 Payment Required challenges, returning a signed payment request that bots verify and settle on-chain in ~400ms.",
            "Provides an NPM library for publishers to gate routes (botlock-sdk) and an agent NPM library (botlock-agent-sdk) to solve challenges.",
          ],
        },
        {
          id: 2,
          name: "botlock.vercel.app",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_1_URL,
          position: "top-10 right-20",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_1_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 6,
      name: "NexusAI",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-7",
      children: [
        {
          id: 1,
          name: "NexusAI Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "A production-grade, distributed multi-agent AI platform orchestrating 8 specialized agents via LangGraph.",
            "Decomposed into 4 independent microservices fronted by a centralized API Gateway, with Redis-backed session management and rate limiting.",
            "Features client-side fuzzy search across conversations, tiered subscription billing via Razorpay, vector search (Qdrant) for PDF RAG, and image analysis.",
          ],
        },
        {
          id: 2,
          name: "nexus-ai.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_2_URL,
          position: "top-20 left-20",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_2_GITHUB,
          position: "top-60 left-5",
        },
      ],
    },
    {
      id: 7,
      name: "fetchit",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "fetchit Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "A full-screen terminal UI (TUI) video downloader built with React and Ink, published on npm as @vedant1521/fetchit.",
            "Supports 2000+ streaming sites (YouTube, X, Instagram, TikTok, etc.) with resolution selection, live size estimates, and clipboard pasting.",
            "Performs parallel playlist downloads (up to 3 concurrent items) and auto-updates the underlying yt-dlp binary directly from the TUI.",
          ],
        },
        {
          id: 2,
          name: "fetchit-cli.vercel.app",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_3_URL,
          position: "top-10 right-20",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_3_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 8,
      name: "NeverSleep",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 left-20",
      windowPosition: "top-[46vh] left-7",
      children: [
        {
          id: 1,
          name: "NeverSleep Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "A utility web application designed to prevent screen sleep using the Screen Wake Lock API.",
            "Features customizable, draggable widgets for a digital clock, Pomodoro timer, battery status, and local to-do lists.",
            "Stores all user preferences, positions, and tasks locally in the browser to ensure persistence across sessions.",
          ],
        },
        {
          id: 2,
          name: "neversleep.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_4_URL,
          position: "top-10 right-20",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_4_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 4,
      name: "about-me.txt",
      icon: "/images/txt.webp",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Meet the Developer Behind the Code",
      description: [
        "Hey! I'm Vedant 👋, a Mathematics and Computing student at Delhi Technological University (DTU), class of 2027.",
        "I recently worked as an AI Full Stack Developer Intern at the Center for Railway Information Systems (CRIS), where I built server monitoring systems and natural language database query interfaces.",
        "I love building complex projects, such as Botlock (a Solana-based bot scraper paywall published as npm packages) and NexusAI (an 8-agent LangGraph platform backed by Redis and microservices).",
        "My skillset ranges from C/C++ and JavaScript/TypeScript to Node.js, React, LangGraph, Docker, and quantitative finance concepts.",
        "I maintain a 9.082 CGPA, scored a perfect 10.0 SGPA in my 5th semester, and ranked in the top 1.9% in JEE Mains 2023.",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/images/pdf.webp",
      kind: "file",
      fileType: "pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 4,
  type: "trash",
  name: "Trash",
  icon: "/icons/trash.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "trash1.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/trash-1.webp",
    },
    {
      id: 2,
      name: "trash2.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-40 left-80",
      imageUrl: "/images/trash-2.webp",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};
